export const teamFeeGroup = [
    {
        name:"显示器购买",
        total:"6666元",
        time:"2019-11-11",
        detail:[
            {
                commodity:"华硕显示器",
                count:"10",
                price:"345",
                purpose:"实验楼东5-12"
            },
            {
                commodity:"华硕键盘",
                count:"10",
                price:"321",
                purpose:"实验楼东5-12"
            },
            {
                commodity:"华硕显示器",
                count:"10",
                price:"345",
                purpose:"实验楼东5-12"
            },
            {
                commodity:"华硕键盘",
                count:"10",
                price:"321",
                purpose:"实验楼东5-12"
            }
        ]
    },
    {
        name:"显示器购买",
        total:"6666元",
        time:"2019-11-11",
        detail:[
            {
                commodity:"华硕显示器",
                count:"10",
                price:"345",
                purpose:"实验楼东5-12"
            },
            {
                commodity:"华硕键盘",
                count:"10",
                price:"321",
                purpose:"实验楼东5-12"
            }
        ]
    },
    {
        name:"显示器购买",
        total:"6666元",
        time:"2019-11-11",
        detail:[
            {
                commodity:"华硕显示器",
                count:"10",
                price:"345",
                purpose:"实验楼东5-12"
            },
            {
                commodity:"华硕键盘",
                count:"10",
                price:"321",
                purpose:"实验楼东5-12"
            }
        ]
    },
    {
        name:"显示器购买",
        total:"6666元",
        time:"2019-11-11",
        detail:[
            {
                commodity:"华硕显示器",
                count:"10",
                price:"345",
                purpose:"实验楼东5-12"
            },
            {
                commodity:"华硕键盘",
                count:"10",
                price:"321",
                purpose:"实验楼东5-12"
            }
        ]
    },{
        name:"显示器购买",
        total:"6666元",
        time:"2019-11-11",
        detail:[
            {
                commodity:"华硕显示器",
                count:"10",
                price:"345",
                purpose:"实验楼东5-12"
            },
            {
                commodity:"华硕键盘",
                count:"10",
                price:"321",
                purpose:"实验楼东5-12"
            }
        ]
    }
]


export const teamProjectGroup = [
    {
        name:"研究生管理系统",
        grade:"2016",
        technology:["HTML","CSS","JS","JAVA"],
        description:"这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统",
        distribution:[
            {
                memberName:"倒霉蛋1号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋2号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋3号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋4号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋5号",
                task:"负责权限部分功能编写"
            }
        ]
    },
    {
        name:"研究生管理系统",
        grade:"2016",
        technology:["HTML","CSS","JS","JAVA"],
        description:"这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统",
        distribution:[
            {
                memberName:"倒霉蛋1号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋2号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋3号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋4号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋5号",
                task:"负责权限部分功能编写"
            }
        ]
    },
    {
        name:"研究生管理系统",
        grade:"2016",
        technology:["HTML","CSS","JS","JAVA"],
        description:"这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统，这就是一个研究生管理系统",
        distribution:[
            {
                memberName:"倒霉蛋1号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋2号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋3号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋4号",
                task:"负责权限部分功能编写"
            },
            {
                memberName:"倒霉蛋5号",
                task:"负责权限部分功能编写"
            }
        ]
    }
]